
export const fake_gridEventsList_ = [
    [],
    [],
    [],
    [],
    [],
    [],
    [],

];

export const fake_gridEventsList = [
    [
        {
            cutPart: null,
            dayNum: 0,
            durationTime: 180,
            eventId: 1,
            firstSegmentId: null,
            id: 2,
            isKeyPoint: true,
            notes: null,
            pushIt: null,
            startTime: 0,
        },
        {
            cutPart: null,
            dayNum: 0,
            durationTime: 180,
            eventId: 2,
            firstSegmentId: null,
            id: 3,
            isKeyPoint: true,
            notes: null,
            pushIt: null,
            startTime: 21600,
        },
        {
            cutPart: null,
            dayNum: 0,
            durationTime: 2700,
            eventId: 10,
            firstSegmentId: null,
            id: 6,
            isKeyPoint: false,
            notes: null,
            pushIt: null,
            startTime: 21780,
        },
        {
            cutPart: null,
            dayNum: 0,
            durationTime: 1500,
            eventId: 4,
            firstSegmentId: null,
            id: 1,
            isKeyPoint: true,
            notes: null,
            pushIt: null,
            startTime: 25200,
        },
        {
            cutPart: null,
            dayNum: 0,
            durationTime: 60,
            eventId: 7,
            firstSegmentId: null,
            id: 4,
            isKeyPoint: false,
            notes: null,
            pushIt: null,
            startTime: 26700,
        },
        {
            cutPart: null,
            dayNum: 0,
            durationTime: 1500,
            eventId: 4,
            firstSegmentId: null,
            id: 5,
            isKeyPoint: true,
            notes: null,
            pushIt: null,
            startTime: 36000,
        },


    ],
    [
        {
            cutPart: null,
            dayNum: 1,
            durationTime: 2700,
            eventId: 10,
            firstSegmentId: null,
            id: 7,
            isKeyPoint: true,
            notes: null,
            pushIt: null,
            startTime: 38809,
        }
    ],
    [
        {
            cutPart: null,
            dayNum: 2,
            durationTime: 60,
            eventId: 7,
            firstSegmentId: null,
            id: 8,
            isKeyPoint: false,
            notes: null,
            pushIt: null,
            startTime: 29970,
        }
    ],
    [],
    [],
    [],
    [],
];